### PR TITLE
adding chkconfig_insteadof_service rule and cleaning up .eggs dir

### PR DESCRIPTION
**Pull request by mschuchard**
small and simple

### CODE REVIEW

**Comment by willthames** [comment]
Any chance you could split this into two commits, one for the eggs change and one for the module change?

They're both good, and I'll accept them both, but would be nicer to have them as separate changes

**Comment by mschuchard** [comment]
done

**Comment by willthames** [comment]
Merged, thanks!

**Comment by willthames** [comment]
Pushed version 2.7.1 including this change to pypi.

3.0.0rc9 has been published to include this change too.

**Pull request merged**
