### PR TITLE
Features/support yaml extension

### PR DESCRIPTION
**Pull request by shaleh**
This one builds on my previous. You can cherry pick out the last commit if you like.

I use main.yaml not .yml.

### CODE REVIEW

**Comment by shaleh** [comment]
Ping.

Like? Dislike? Complaints?

**Comment by willthames** [comment]
I've cherrypicked 94418d1 onto the main repository

**Comment by willthames** [comment]
Apologies for late response, I was on holiday in August and then forgot all about it!

**Comment by shaleh** [comment]
No worries. 

On September 19, 2015 9:25:07 PM PDT, Will Thames <notifications@github.com> wrote:
>Apologies for late response, I was on holiday in August and then forgot
>all about it!
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/willthames/ansible-lint/pull/69#issuecomment-141746436

-- 
Sent from my Android phone with K-9 Mail. Please excuse my brevity.

**Pull request closed without merging**
