### PR TITLE
Add a test harness for individual rules

### PR DESCRIPTION
**Pull request by shaleh**
Simple test setup to allow testing individual rules directly.

### CODE REVIEW

**Comment by willthames** [comment]
I don't want the rules imports in rules/__init__.py - can this work without that?

**Comment by shaleh** [comment]
I will see what can be done.

**Comment by shaleh** [comment]
I synced the branch and removed the imports. Sorry, they were from earlier testing.

I have verified the code against py27 and py34.

**Comment by willthames** [comment]
@shaleh I'm sorry that this never got looked at again properly at the time. 

The solution used by test/TestOctalPermissions.py seems good enough for testing individual rules though.

I'm going to close this now

**Comment by shaleh** [comment]
No worries. Thanks for resolving this.

**Pull request closed without merging**
