### PR TITLE
New rules

### PR DESCRIPTION
**Pull request by willthames**
These commits will form the basis of ansible-lint v3 and include three new default rules

* All tasks should have a name
* Packages do not use `state=latest`
* Commands check whether stuff should/will change using `changes/removes/changed_when`

Let me know if any of these are show stoppers, or if you have feedback

Note that v3 will also include #134, #135 and #136 but they'll probably get into v2.5.x or similar

Notifying common contributors ansible-lint for heads up

@pabelanger 
@mschuchard 
@MiLk 
@siddharthist 
@dmsimard 
@shaleh 
@msabramo

### CODE REVIEW

**Comment by MiLk** [comment]
If you want to make a rule throw an error when `state=latest` is used, you might want to throw an error when `state=present` is used without any version specified, because your cluster might end up with different versions of software if you don't provision all the nodes at the same time.

You might want to be able to use `state=latest` for things like `openssl` which should always be in the latest version. So that you don't need to release a new version of your role every time they fix a major issue.

**Comment by willthames** [comment]
@MiLk, you're quite right about `state=present`, the only difficulty will be checking that the packages have a version, particularly with `with_items`, but I'll give it a go.

With openssl, I guess that's a good time to use `skip_ansible_latest` tag.

**Comment by willthames** [comment]
We do have some roles where the specific version of a minor software dependency isn't that important, and look a little like

In particular with tasks that are of the form:

```
- yum: state=present name={{ item }}
  with_items:
  - application-{{ application_version }}
  - minor-dependency{{ "-" ~ minor_dependency_version if minor_dependency_version is defined else "" }}
```
I am not at all sure how we'd check the former has a version, let alone the latter!

**Comment by MiLk** [comment]
Sure. Let's say it's ok and you can use `skip_ansible_lint` for `openssl`.

**Comment by willthames** [comment]
There are now some breaking changes in 3.0.0 as a result of #107 

If you have your own custom modules and use `matchtask`, the keys for the `task['action']` have changed to avoid clashes.

**Comment by mschuchard** [comment]
#118 seems to have already made it into HEAD.

**Comment by willthames** [comment]
These changes have been merged and are in the released version 3.

**Pull request closed without merging**
