### PR TITLE
PYYaml dependency missing from setup

### PR DESCRIPTION
**Pull request by nickpack**
...dependent on ansible installation method this package may not be installed

### CODE REVIEW

**Comment by nickpack** [comment]
@willthames Sorry, only just got to this. Version bumped and commits squashed as requested.

**Comment by willthames** [comment]
It's showing up as two commits here so the squash may not have worked quite right.

`git rebase -i HEAD^^` and change the second pick to a fixup (or squash if you prefer to edit the message) should do the trick, then `git push -f` the result.

**Comment by nickpack** [comment]
@willthames Sorry, was half asleep when I did it - all fixed :)

**Comment by willthames** [comment]
I forgot to ask you to rebase it against latest (which was at 2.0.2) - I changed version to 2.0.3 while merging your commit so no harm done.

I'll update pypi too.

**Pull request merged**
