### PR TITLE
Renaming module parameters into __ansible_module__

### PR DESCRIPTION
**Pull request by Yannig**
Avoid collision with action taking module arguments.

Fix for https://github.com/willthames/ansible-lint/issues/106

### CODE REVIEW

**Comment by willthames** [comment]
Hi, I don't quite understand the motivation for this one.

Can you let me know what fails in the absence of this? (if one of the tests would fail in the absence of this change, that would be ideal)

**Comment by Yannig** [comment]
Well, I have profided an example in https://github.com/willthames/ansible-lint/issues/106 but in my case, the following instruction result in a crash:

```yaml
- set_fact:
    type="WorkManager"
    module="workmanager"
```

**Comment by atward** [comment]
This convention should also be done for `module_arguments`

**Comment by willthames** [comment]
I'll look at getting this into v3. 

Apologies for the delay, I didn't want to take in any breaking changes, but v3 will be a good opportunity.

**Comment by Yannig** [comment]
@willthames no problem :)

**Comment by willthames** [comment]
This is in v3.0 branch and ready for testing with the 3.0.0rc6 release to pypi.

**Comment by willthames** [comment]
These changes have been merged into the released version 3

**Comment by willthames** [comment]
Thank you for your contribution.

**Comment by Yannig** [comment]
You're welcome :)

**Pull request closed without merging**
