### PR TITLE
Fix when roles have embeded modules

### PR DESCRIPTION
**Pull request by cloudnull**
This change updates the v2 task to try and use the module parse method
from ansible 2 and will fall back to the v1 normalization method if it
fails due because of an AnsibleParserError.

Closes-Bug: #145
Signed-off-by: Kevin Carter <kevin.carter@rackspace.com>

### CODE REVIEW

**Comment by mgagne** [comment]
Works for me now! Thanks!

**Comment by willthames** [comment]
I'll merge this if I can't work out how Ansible detects embedded modules when doing its own parsing (really I want to use Ansible's libraries to do as much as I can)

**Comment by willthames** [comment]
See #145. I propose closing this if it's been fixed with latest v2.7 and v3.0 releases

**Comment by cloudnull** [comment]
Everything looks like its working now. So this PR may no longer be needed. Thank you for everything.

**Pull request closed without merging**
