### PR TITLE
Sort matches by linenumber

### PR DESCRIPTION
**Pull request by adrianmoisey**
For a sorted output

### CODE REVIEW

**Comment by willthames** [comment]
Can you update this PR to include a before and after as it's difficult to see the change without that context. I assume this will go from issues sorted by rule number to issues sorted by line number, which seems sensible, but would like to see.

**Comment by adrianmoisey** [comment]
Before:
```
$ ansible-lint -p has_errors.yml
has_errors.yml:9: [EANSIBLE0012] Commands should not change things if nothing needs doing
has_errors.yml:12: [EANSIBLE0012] Commands should not change things if nothing needs doing
has_errors.yml:24: [EANSIBLE0012] Commands should not change things if nothing needs doing
has_errors.yml:24: [EANSIBLE0006] git used in place of git module
has_errors.yml:27: [EANSIBLE0006] git used in place of git module
has_errors.yml:15: [EANSIBLE0004] Git checkouts must contain explicit version
has_errors.yml:18: [EANSIBLE0004] Git checkouts must contain explicit version
has_errors.yml:30: [EANSIBLE0004] Git checkouts must contain explicit version
has_errors.yml:39: [EANSIBLE0010] Package installs should not use latest
has_errors.yml:44: [EANSIBLE0010] Package installs should not use latest
has_errors.yml:13: [EANSIBLE0002] Trailing whitespace
has_errors.yml:35: [EANSIBLE0002] Trailing whitespace
```
After:
$ ansible-lint -p has_errors.yml
has_errors.yml:9: [EANSIBLE0012] Commands should not change things if nothing needs doing
has_errors.yml:12: [EANSIBLE0012] Commands should not change things if nothing needs doing
has_errors.yml:13: [EANSIBLE0002] Trailing whitespace
has_errors.yml:15: [EANSIBLE0004] Git checkouts must contain explicit version
has_errors.yml:18: [EANSIBLE0004] Git checkouts must contain explicit version
has_errors.yml:24: [EANSIBLE0012] Commands should not change things if nothing needs doing
has_errors.yml:24: [EANSIBLE0006] git used in place of git module
has_errors.yml:27: [EANSIBLE0006] git used in place of git module
has_errors.yml:30: [EANSIBLE0004] Git checkouts must contain explicit version
has_errors.yml:35: [EANSIBLE0002] Trailing whitespace
has_errors.yml:39: [EANSIBLE0010] Package installs should not use latest
has_errors.yml:44: [EANSIBLE0010] Package installs should not use latest
```

Before doesn't seem to be numerically sorted correctly.

**Comment by willthames** [comment]
can we also add a secondary sort key for the rule id?

has_errors.yml:24 should probably list rule 6 before rule 12.

**Comment by adrianmoisey** [comment]
Updated, here's the new output:
```
$ ansible-lint -p has_errors.yml
has_errors.yml:9: [EANSIBLE0012] Commands should not change things if nothing needs doing
has_errors.yml:12: [EANSIBLE0012] Commands should not change things if nothing needs doing
has_errors.yml:13: [EANSIBLE0002] Trailing whitespace
has_errors.yml:15: [EANSIBLE0004] Git checkouts must contain explicit version
has_errors.yml:18: [EANSIBLE0004] Git checkouts must contain explicit version
has_errors.yml:24: [EANSIBLE0006] git used in place of git module
has_errors.yml:24: [EANSIBLE0012] Commands should not change things if nothing needs doing
has_errors.yml:27: [EANSIBLE0006] git used in place of git module
has_errors.yml:30: [EANSIBLE0004] Git checkouts must contain explicit version
has_errors.yml:35: [EANSIBLE0002] Trailing whitespace
has_errors.yml:39: [EANSIBLE0010] Package installs should not use latest
has_errors.yml:44: [EANSIBLE0010] Package installs should not use latest
```

**Comment by willthames** [comment]
Can you fix Sory to Sort in your last commit message and repush, and we should be good to merge.

**Comment by adrianmoisey** [comment]
Sorrt about that! ;) Fixed

**Comment by willthames** [comment]
Merged, thanks.

**Comment by willthames** [comment]
v3.4.4 tagged and pushed to pypi

**Comment by adrianmoisey** [comment]
\o/ Thanks

**Comment by straight-shoota** [comment]
I was quite confused when I first ran ansible-lint. Sorting should take into account that not all line numbers refer to the same file... This is quite akward and I'd suggest to sort by file first, then by line number and rule.

**Pull request merged**
