### PR TITLE
Tasks/py cleanup

### PR DESCRIPTION
**Pull request by shaleh**
Runs on Py3.4. 
flake8/pep8 cleanups. Allowed for longer lines.
General Python cleanups. [] v. list() etc.

Removed code like the following

```
def foo(arg1, arg2=set()):
    pass
```

leads to nasty bugs. http://docs.python-guide.org/en/latest/writing/gotchas/#mutable-default-arguments has details.

This is like @kovacsbalu's pull request but I think mine has more changes.

### CODE REVIEW

**Comment by willthames** [comment]
I don't really want widespread formatting changes only (I'll accept pylint/pep8/pyflakes improvements as part of features or bug fixes). I do state this in https://github.com/willthames/ansible-lint/blob/master/CONTRIBUTING.md#standards

Certainly improvements such as d882157 would be accepted on their own.

**Comment by willthames** [comment]
5d32e65 might be accepted if I had some context as to what it was breaking.

**Comment by shaleh** [comment]
Your code is not following standard Python idioms. Yes it is your code but it makes it harder for anyone else to contribute.

No offense intended but I took the code as "my first Python app" so I submitted updates to help you use more standard Python. You are welcome to ignore the suggestion. No harm, no foul.

**Comment by shaleh** [comment]
I am making a new pull request to that just does the flake8/py34 update.

**Pull request closed without merging**
