### PR TITLE
Minimal changes & test to fix issue 263 - vault password for encrypted values

### PR DESCRIPTION
**Pull request by mozz100**
Ansible 2.3+ allows variables to be encrypted *within* YAML files. Pass a default vault_password to the functions that parse YAML.
Include a test to check this raises no exceptions under Ansible 2.3+

### CODE REVIEW

**Comment by mozz100** [comment]
Hey just checking in on this.  I think the same thing happened as on pull request #269 with Travis.  The tests pass if I run them locally.

**Comment by willthames** [comment]
Sorry I missed this earlier, this looks pretty reasonable - I'll do some quick tests and then should be good to merge

**Comment by willthames** [comment]
I can reproduce the test failures just by running `tox`. I ensured `PYTHONPATH` was unset and I wasn't inside a virtualenv too.

**Comment by mozz100** [comment]
I don't understand what's going on, then.  I can reproduce the test _success_ by running `tox` :confused:.  `PYTHONPATH` is not set, no virtualenv.  Below is what I'm doing, on a completely clean ubuntu 14 machine.  If you can see what I'm doing wrong, I'll fix it and get the tests passing again.

```bash
cat /etc/lsb-release
#  DISTRIB_ID=Ubuntu
#  DISTRIB_RELEASE=14.04
#  DISTRIB_CODENAME=trusty
#  DISTRIB_DESCRIPTION="Ubuntu 14.04.1 LTS"

# install requirements
sudo apt-get update
sudo apt-get install -y git python-pip python-dev python3-dev libssl-dev
python --version   # Python 2.7.6
python3 --version  # Python 3.4.3

# install tox
sudo pip install tox

# clone repo from mozz100; minimal-vault-password branch
cd ~; mkdir -p src; cd src
git clone -b minimal-vault-password https://github.com/mozz100/ansible-lint.git
cd ansible-lint

# run tox
tox
#  GLOB sdist-make: /home/ubuntu/ansible-lint/setup.py
#  py27-ansible19 create: /home/ubuntu/ansible-lint/.tox/py27-ansible19
#  ....
#  ....
#  ....
#  py27-ansible19: commands succeeded
#  py27-ansible20: commands succeeded
#  py27-ansible21: commands succeeded
#  py27-ansible22: commands succeeded
#  py27-ansibledevel: commands succeeded
#  py34-ansible22: commands succeeded
#  py34-ansibledevel: commands succeeded
#  flake8: commands succeeded
#  congratulations :)
```

**Comment by willthames** [comment]
Can you include what versions of libraries are installed for just one of
the runs, eg the 2.2 run

**Comment by willthames** [comment]
Here's my ansible22 library versions:
```
py27-ansible22 inst-nodeps: /Users/will/src/ansible-lint/.tox/dist/ansible-lint-3.4.13.zip
py27-ansible22 installed: You are using pip version 8.0.2, however version 9.0.1 is available.,You should consider upgrading via the 'pip install --upgrade pip' command.,ansible==2.2.1.0,ansible-lint==3.4.13,cffi==1.9.1,configparser==3.5.0,cryptography==1.7.2,enum34==1.1.6,flake8==3.3.0,idna==2.2,ipaddress==1.0.18,Jinja2==2.8.1,MarkupSafe==0.23,mccabe==0.6.1,nose==1.3.7,paramiko==2.1.1,pep8-naming==0.4.1,pluggy==0.4.0,py==1.4.32,pyasn1==0.2.2,pycodestyle==2.3.1,pycparser==2.17,pycrypto==2.6.1,pyflakes==1.5.0,PyYAML==3.12,six==1.10.0,tox==2.6.0,virtualenv==15.1.0,wheel==0.26.0
py27-ansible22 runtests: PYTHONHASHSEED='3214951874'
py27-ansible22 runtests: commands[0] | nosetests
cEEEEEEEE.....EEEE.........EcEEEE..EEEEEE...EEEEEEEEEEEE..............
======================================================================
ERROR: test_file_negative (test.TestAlwaysRunRule.TestAlwaysRun)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/will/src/ansible-lint/test/TestAlwaysRunRule.py", line 20, in test_file_negative
    errs = bad_runner.run()
  File "/Users/will/src/ansible-lint/lib/ansiblelint/__init__.py", line 243, in run
    skip_list=set(self.skip_list)))
  File "/Users/will/src/ansible-lint/lib/ansiblelint/__init__.py", line 139, in run
    matches.extend(rule.matchtasks(playbookfile, text))
  File "/Users/will/src/ansible-lint/lib/ansiblelint/__init__.py", line 66, in matchtasks
    yaml = ansiblelint.utils.parse_yaml_linenumbers(text, file['path'])
  File "/Users/will/src/ansible-lint/lib/ansiblelint/utils.py", line 543, in parse_yaml_linenumbers
    data = loader.get_single_data()
  File "/Users/will/src/ansible-lint/.tox/py27-ansible22/lib/python2.7/site-packages/yaml/constructor.py", line 39, in get_single_data
    return self.construct_document(node)
  File "/Users/will/src/ansible-lint/.tox/py27-ansible22/lib/python2.7/site-packages/yaml/constructor.py", line 48, in construct_document
    for dummy in generator:
  File "/Users/will/src/ansible-lint/.tox/py27-ansible22/lib/python2.7/site-packages/ansible/parsing/yaml/constructor.py", line 49, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/Users/will/src/ansible-lint/lib/ansiblelint/utils.py", line 528, in construct_mapping
    mapping[LINE_NUMBER_KEY] = node.__line__
AttributeError: 'MappingNode' object has no attribute '__line__'
```

**Comment by mozz100** [comment]
Thanks for looking into it. I've attached full output from my run of tox: 
[tox_output.txt](https://github.com/willthames/ansible-lint/files/1145834/tox_output.txt)

**Comment by mozz100** [comment]
...and if I extract the corresponding bit near `py27-ansible22` it is: 

ansible==2.2.3.0,ansible-lint==3.4.13,asn1crypto==0.22.0,bcrypt==3.1.3,cffi==1.10.0,configparser==3.5.0,cryptography==1.9,enum34==1.1.6,flake8==3.3.0,idna==2.5,ipaddress==1.0.18,Jinja2==2.9.6,MarkupSafe==1.0,mccabe==0.6.1,nose==1.3.7,paramiko==2.2.1,pep8-naming==0.4.1,pluggy==0.4.0,py==1.4.34,pyasn1==0.2.3,pycodestyle==2.3.1,pycparser==2.18,pycrypto==2.6.1,pyflakes==1.5.0,PyNaCl==1.1.2,PyYAML==3.12,six==1.10.0,tox==2.7.0,virtualenv==15.1.0

```
py27-ansible22 create: /home/ubuntu/src/ansible-lint/.tox/py27-ansible22
py27-ansible22 installdeps: ansible>=2.2,<2.3, -rtest-deps.txt
py27-ansible22 inst: /home/ubuntu/src/ansible-lint/.tox/dist/ansible-lint-3.4.13.zip
py27-ansible22 installed: ansible==2.2.3.0,ansible-lint==3.4.13,asn1crypto==0.22.0,bcrypt==3.1.3,cffi==1.10.0,configparser==3.5.0,cryptography==1.9,enum34==1.1.6,flake8==3.3.0,idna==2.5,ipaddress==1.0.18,Jinja2==2.9.6,MarkupSafe==1.0,mccabe==0.6.1,nose==1.3.7,paramiko==2.2.1,pep8-naming==0.4.1,pluggy==0.4.0,py==1.4.34,pyasn1==0.2.3,pycodestyle==2.3.1,pycparser==2.18,pycrypto==2.6.1,pyflakes==1.5.0,PyNaCl==1.1.2,PyYAML==3.12,six==1.10.0,tox==2.7.0,virtualenv==15.1.0
py27-ansible22 runtests: PYTHONHASHSEED='1422194640'
py27-ansible22 runtests: commands[0] | nosetests
............................WARNING: Couldn't open /home/ubuntu/src/ansible-lint/test/doesnotexist.yml - No such file or directory
........................................
----------------------------------------------------------------------
Ran 68 tests in 2.422s

OK
```

**Comment by willthames** [comment]
I can't reproduce it through tox on a fresh host but I can running

```
PYTHONPATH=lib python lib/ansiblelint/main/__init__.py examples/include.yml 
/ansible-lint.git
```

Unfortunately I have no real idea *why* it's failing there, and why it works normally.

**Comment by mozz100** [comment]
Thanks for looking into it - I ran the same command and saw no issues :-).  I'm afraid I can't spend any more time on working this out.  If you don't use it directly, hopefully just the approach (passing a dummy password, ignoring the value) will be of use for ansible-lint in future. I certainly plan to use ansible's new in-file encrypted secrets extensively; I find that feature very helpful in identifying & tracking where variables are defined.  So I'll use my own branch until something like this is merged into ansible-lint.

Thanks for sharing this tool - I really appreciated it and it helped me clean up a fairly large set of roles and playbooks.

**Comment by willthames** [comment]
Thanks for the feedback, glad ansible-lint is helpful. I don't have heaps of time for this either, but would like to understand why the tests are failing, so I'll try and keep plugging away at it when I do have some spare time.

**Comment by willthames** [comment]
Fixed through #332

**Pull request closed without merging**
