### PR TITLE
Be flake8 compliant.

### PR DESCRIPTION
**Pull request by shaleh**
Add flake8 config to setup.cfg.
Clear up most of the flake8 complaints.

### CODE REVIEW

**Comment by willthames** [comment]
It's been a while since I've looked at this - it seems that it implements most of the python 3 readiness too.

If you want to rebase this change, I'll definitely look at it favourably now.

**Comment by willthames** [comment]
I'll probably add flake8 automation to the tox test suite (unless you're keen to) and potentially travis CI too - I'd like to improve standards across the project so that all contributions, mine included (or perhaps especially), are held to a reasonable coding standard.

**Comment by shaleh** [comment]
Ok, branch has been rebased. flake8 has been added to tox.

I needed to bump the line length from 100 to 110 because there is a line 101 chars long :-)

**Comment by willthames** [comment]
Great, thank you. I have a future commit that brings line length down to 100.

**Pull request merged**
