### PR TITLE
Allow templating of playbook_dir

### LINKED ISSUE #113: Misreading of include containing playbook_dir
I just got the following traceback which can be reproduced as follows:
```
$ git clone https://github.com/CiscoCloud/mantl
$ find . -name "*.yml" -exec ansible-lint {} \; -exec echo "PLAYBOOK: " {} \;                                                                                 
Traceback (most recent call last):
  File "/home/siddharthist/.virtualenvs/mantl/bin/ansible-lint", line 116, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/home/siddharthist/.virtualenvs/mantl/bin/ansible-lint", line 103, in main
    matches = runner.run()
  File "/home/siddharthist/.virtualenvs/mantl/lib/python2.7/site-packages/ansiblelint/__init__.py", line 211, in run
    skip_list=set(self.skip_list)))
  File "/home/siddharthist/.virtualenvs/mantl/lib/python2.7/site-packages/ansiblelint/__init__.py", line 115, in run
    with open(playbookfile['path'], 'Ur') as f:
IOError: [Errno 2] No such file or directory: u'/home/siddharthist/Dropbox/code/asteris/mantl/addons/playbooks/check-requirements.yml'
Traceback (most recent call last):
  File "/home/siddharthist/.virtualenvs/mantl/bin/ansible-lint", line 116, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/home/siddharthist/.virtualenvs/mantl/bin/ansible-lint", line 103, in main
    matches = runner.run()
  File "/home/siddharthist/.virtualenvs/mantl/lib/python2.7/site-packages/ansiblelint/__init__.py", line 211, in run
    skip_list=set(self.skip_list)))
  File "/home/siddharthist/.virtualenvs/mantl/lib/python2.7/site-packages/ansiblelint/__init__.py", line 115, in run
    with open(playbookfile['path'], 'Ur') as f:
IOError: [Errno 2] No such file or directory: u'/home/siddharthist/Dropbox/code/asteris/mantl/addons/playbooks/check-requirements.yml'
PLAYBOOK  ./addons/iptables.yml
```
Looks like there's a problem with parsing [the include line in that playbook](https://github.com/CiscoCloud/mantl/blob/da44f77a50ba1908b8e84eb190e78a3ffb496824/addons/elk.yml#L7).

### PR DESCRIPTION
**Pull request by willthames**
`{{playbook_dir}}` will be expanded relative to the playbook
being linted.

Fixes #113

### CODE REVIEW

**Comment by siddharthist** [comment]
This doesn't seem to fix the issue:
```
(mantl) ansible-lint ➤ git branch
  master
* playbook_dir_templating
```
```
(mantl) mantl ➤ find . -name "*.yml" -exec ../ansible-lint/bin/ansible-lint {} +
Traceback (most recent call last):
  File "../ansible-lint/bin/ansible-lint", line 116, in <module>
    sys.exit(main(sys.argv[1:]))
  File "../ansible-lint/bin/ansible-lint", line 103, in main
    matches = runner.run()
  File "/home/siddharthist/.virtualenvs/mantl/lib/python2.7/site-packages/ansiblelint/__init__.py", line 211, in run
    skip_list=set(self.skip_list)))
  File "/home/siddharthist/.virtualenvs/mantl/lib/python2.7/site-packages/ansiblelint/__init__.py", line 115, in run
    with open(playbookfile['path'], 'Ur') as f:
IOError: [Errno 2] No such file or directory: u'/home/siddharthist/Dropbox/code/asteris/mantl/addons/playbooks/check-requirements.yml'
```

**Comment by willthames** [comment]
Is your PYTHONPATH set to use the right ansible-lint?

What does `../ansible-lint/bin/ansible-lint --version` say

**Comment by siddharthist** [comment]
@willthames I think you're right!
```
(ansible-lint) mantl ➤ ../ansible-lint/bin/ansible-lint --version
Traceback (most recent call last):
  File "../ansible-lint/bin/ansible-lint", line 30, in <module>
    import ansiblelint
ImportError: No module named 'ansiblelint'
```
How could I fix that?

**Comment by siddharthist** [comment]
@willthames It works! Thank you for your help and attention to this issue :)

**Comment by siddharthist** [comment]
@willthames When could we expect a release with this change?

**Comment by willthames** [comment]
@siddharthist thanks for the friendly reminder. I've merged this and uploaded it as 2.4.0 to pypi.

**Pull request merged**
