### PR TITLE
Fix issue #54

### PR DESCRIPTION
**Pull request by charleswhchan**
Modified `-x` option to accept tags as well as ids.

### CODE REVIEW

**Comment by charleswhchan** [comment]
@willthames Any comments?

**Comment by willthames** [comment]
Apologies @charleswhchan for not responding earlier. 

This looks good to me.

**Comment by charleswhchan** [comment]
Thanks @willthames. No worries.

On a secondary note: Are you planning to cut a release anytime soon? Or do you have other features/enhancements in mind?

**Comment by willthames** [comment]
@charleswhchan - good point, I'll do that now

**Comment by willthames** [comment]
2.1.3 has been uploaded to pypi

**Comment by charleswhchan** [comment]
@willthames: Many thanks! :smile:

**Pull request merged**
